imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, webroot/css/*, 3pp/]

tools:
    external_code_coverage: true
#        timeout: 600 # Timeout in seconds.

checks:
    php:
        code_rating: true
        duplication: true
